SELECT * FROM sample31;
SELECT * FROM sample31 ORDER BY age;
SELECT* FROM sample31 ORDER BY address;
SELECT* FROM sample31 ORDER BY age DESC;
SELECT* FROM sample31 ORDER BY age ASC;
SELECT* FROM sample31 ORDER BY a;


SELECT* FROM sample32;
SELECT* FROM sample32 ORDER BY a, b;
SELECT* FROM sample32 ORDER BY b, a;
SELECT* FROM sample32 ORDER BY a ASC, b DESC;

SELECT* FROM sample33;
SELECT* FROM sample33 LIMIT 3;
SELECT* FROM sample33 ORDER BY no DESC LIMIT 3;
SELECT* FROM sample33 LIMIT 3 OFFSET 0;
SELECT* FROM sample33 LIMIT 3 OFFSET 3;


